# Generated by Django 3.0.5 on 2020-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200509_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='calendar',
            name='content',
            field=models.CharField(default='', max_length=250, verbose_name='Content:'),
        ),
    ]
