# Generated by Django 3.0.5 on 2020-05-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_calendar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='link',
            field=models.CharField(max_length=250, null=True, verbose_name='Link:'),
        ),
    ]
