# Generated by Django 3.0.5 on 2020-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20200509_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='link',
            field=models.CharField(default=' ', max_length=250, verbose_name='Link:'),
        ),
    ]
