# Generated by Django 3.0.5 on 2020-05-10 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20200509_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendar',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
