# Generated by Django 3.0.5 on 2020-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20200510_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_to',
            field=models.DateField(),
        ),
    ]
