# Generated by Django 3.0.5 on 2020-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20200510_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='Content:'),
        ),
    ]
